package com.codesroots.live_venodr.models.current_order_model

data class CurrentOrderModelItem(
    var billing_address: Any,
    var billing_address_id: Int,
    var branch_id: Int,
    var canceled_reason: String,
    var commission: Int,
    var created: String,
    var delivery_comment: String,
    var delivery_id: Int,
    var delivery_serivce: Int,
    var delivery_time: Int,
    var discount: Int,
    var id: Int,
    var modified: String,
    var name: String,
    var notes: String,
    var offer_discount: Int,
    var offer_id: Int,
    var order_details: List<Any>,
    var order_status_id: Int,
    var paymenttype: Any,
    var paymenttype_id: Int,
    var phone: String,
    var sub_total: Int,
    var takeway: Int,
    var taxes: Int,
    var test_orders: Int,
    var total: Int,
    var user_id: Int,
    var wallet_discount: Int,
    var wallets_id: Int
)