package com.codesroots.live.models.ordermodel

data class OrderModel(
    var billing_address: Any?=null,
    var billing_address_id: Int?=null,
    var branch_id: Int?=null,
    var branches: Branches?=null,
    var canceled_reason: String?=null,
    var commission: Int?=null,
    var created: String?=null,
    var delivery_comment: String?=null,
    var delivery_id: Int?=null,
    var delivery_serivce: Int?=null,
    var delivery_time: Int?=null,
    var discount: Int?=null,
    var id: Int?=null,
    var modified: String?=null,
    var notes: String?=null,
    var offer_discount: Int?=null,
    var offer_id: Int?=null,
    var order_status: Any?=null,
    var order_status_id: Int?=null,
    var paymenttype: Any?=null,
    var paymenttype_id: Int?=null,
    var sub_total: Int?=null,
    var takeway: Int?=null,
    var taxes: Int?=null,
    var test_orders: Int?=null,
    var total: Double?=null,
    var user_id: Int?=null,
    var users: Any?=null,
    var wallet_discount: Int?=null,
    var wallets_id: Int?=null,
    )